apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssd
provisioner: predic8.de/local-directory
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  baseDir: /mnt/ssd
